CREATE TYPE user_enum AS ENUM (
'USER',
'ORGANIZATION',
'DIAGNOSTIC',
'HOSPITAL',
'ADMIN');

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email VARCHAR(255) UNIQUE,
  nin VARCHAR(11) NULL,
  password VARCHAR(255) NOT NULL,
  user_type user_enum NOT NULL,
  address JSONB NULL,
  contact JSONB NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
