// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, userID string) (*Organization, error)
	GetOrganization(ctx context.Context, id string) (*Organization, error)
	GetOrganizationByUserID(ctx context.Context, userID string) (*Organization, error)
}

var _ Querier = (*Queries)(nil)
