// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: records.sql

package db

import (
	"context"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
  organization_id,
  user_id,
  record
) VALUES  (
  $1, $2, $3
) RETURNING id, organization_id, user_id, record, created_at, updated_at
`

type CreateRecordParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	UserID         string `db:"user_id" json:"user_id"`
	Record         string `db:"record" json:"record"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (*Record, error) {
	row := q.db.QueryRow(ctx, createRecord, arg.OrganizationID, arg.UserID, arg.Record)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Record,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, organization_id, user_id, record, created_at, updated_at FROM records where id = $1
`

func (q *Queries) GetRecord(ctx context.Context, id string) (*Record, error) {
	row := q.db.QueryRow(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Record,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRecords = `-- name: GetRecords :many
SELECT id, organization_id, user_id, record, created_at, updated_at FROM records where organization_id = $1
LIMIT 50
`

func (q *Queries) GetRecords(ctx context.Context, organizationID string) ([]*Record, error) {
	rows, err := q.db.Query(ctx, getRecords, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Record,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadRecord = `-- name: UploadRecord :one
INSERT INTO uploads (
  organization_id,
  user_id,
  scan_title,
  file_name
) VALUES  (
  $1, $2, $3, $4
) RETURNING id, organization_id, user_id, scan_title, file_name, created_at, updated_at
`

type UploadRecordParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	UserID         string `db:"user_id" json:"user_id"`
	ScanTitle      string `db:"scan_title" json:"scan_title"`
	FileName       string `db:"file_name" json:"file_name"`
}

func (q *Queries) UploadRecord(ctx context.Context, arg UploadRecordParams) (*Upload, error) {
	row := q.db.QueryRow(ctx, uploadRecord,
		arg.OrganizationID,
		arg.UserID,
		arg.ScanTitle,
		arg.FileName,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.ScanTitle,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
