// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: diagnostic.sql

package db

import (
	"context"
)

const createDiagnostic = `-- name: CreateDiagnostic :one
INSERT INTO diagnostics (
  user_id
) VALUES  (
  $1
) RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateDiagnostic(ctx context.Context, userID string) (*Diagnostic, error) {
	row := q.db.QueryRow(ctx, createDiagnostic, userID)
	var i Diagnostic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDiagnostic = `-- name: GetDiagnostic :one
SELECT id, user_id, created_at, updated_at FROM diagnostics WHERE id = $1
`

func (q *Queries) GetDiagnostic(ctx context.Context, id string) (*Diagnostic, error) {
	row := q.db.QueryRow(ctx, getDiagnostic, id)
	var i Diagnostic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
