// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDiagnostic(ctx context.Context, userID string) (*Diagnostic, error)
	CreateOrganization(ctx context.Context, userID string) (*Organization, error)
	CreateRecord(ctx context.Context, arg CreateRecordParams) (*Record, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (*DiagnosticSchedule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeleteSchedule(ctx context.Context, id string) (*DiagnosticSchedule, error)
	GetDiagnostic(ctx context.Context, id string) (*Diagnostic, error)
	GetOrganization(ctx context.Context, id string) (*Organization, error)
	GetOrganizationByUserID(ctx context.Context, userID string) (*Organization, error)
	GetRecord(ctx context.Context, id string) (*Record, error)
	GetRecords(ctx context.Context, organizationID string) ([]*Record, error)
	GetRecordsByUser(ctx context.Context, userID string) ([]*Record, error)
	GetRecordsByUserAndScanTitle(ctx context.Context, arg GetRecordsByUserAndScanTitleParams) ([]*Record, error)
	GetSchedule(ctx context.Context, id string) (*DiagnosticSchedule, error)
	GetSchedules(ctx context.Context, arg GetSchedulesParams) ([]*DiagnosticSchedule, error)
	GetSchedulesByCentre(ctx context.Context, arg GetSchedulesByCentreParams) ([]*DiagnosticSchedule, error)
	GetSchedulesByStatus(ctx context.Context, arg GetSchedulesByStatusParams) ([]*DiagnosticSchedule, error)
	GetUser(ctx context.Context, id string) (*User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (*User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]*User, error)
	SearchRecordByNin(ctx context.Context, nin pgtype.Text) ([]*SearchRecordByNinRow, error)
	SearchRecordByNinAndScanTitle(ctx context.Context, arg SearchRecordByNinAndScanTitleParams) ([]*SearchRecordByNinAndScanTitleRow, error)
	UpdateNin(ctx context.Context, arg UpdateNinParams) (*UpdateNinRow, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (*DiagnosticSchedule, error)
	UploadRecord(ctx context.Context, arg UploadRecordParams) (*Upload, error)
}

var _ Querier = (*Queries)(nil)
