// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  nin,
  password,
  user_type
) VALUES  (
  $1, $2, $3, $4
) RETURNING id, email, nin, user_type, created_at, updated_at
`

type CreateUserParams struct {
	Email    pgtype.Text `db:"email" json:"email"`
	Nin      pgtype.Text `db:"nin" json:"nin"`
	Password string      `db:"password" json:"password"`
	UserType UserEnum    `db:"user_type" json:"user_type"`
}

type CreateUserRow struct {
	ID        string             `db:"id" json:"id"`
	Email     pgtype.Text        `db:"email" json:"email"`
	Nin       pgtype.Text        `db:"nin" json:"nin"`
	UserType  UserEnum           `db:"user_type" json:"user_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Nin,
		arg.Password,
		arg.UserType,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nin,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, nin, password, user_type, address, contact, created_at, updated_at FROM users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nin,
		&i.Password,
		&i.UserType,
		&i.Address,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, nin, password, user_type, address, contact, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nin,
		&i.Password,
		&i.UserType,
		&i.Address,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, nin, password, user_type, address, contact, created_at, updated_at FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nin,
			&i.Password,
			&i.UserType,
			&i.Address,
			&i.Contact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNin = `-- name: UpdateNin :one
UPDATE users
SET
  nin = COALESCE($1, nin),
  updated_at = NOW()
WHERE id = $2
RETURNING id, email, user_type, created_at, updated_at
`

type UpdateNinParams struct {
	Nin pgtype.Text `db:"nin" json:"nin"`
	ID  string      `db:"id" json:"id"`
}

type UpdateNinRow struct {
	ID        string             `db:"id" json:"id"`
	Email     pgtype.Text        `db:"email" json:"email"`
	UserType  UserEnum           `db:"user_type" json:"user_type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateNin(ctx context.Context, arg UpdateNinParams) (*UpdateNinRow, error) {
	row := q.db.QueryRow(ctx, updateNin, arg.Nin, arg.ID)
	var i UpdateNinRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
